# -*- coding: utf-8 -*-
"""plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YxRy-cBojW9otjiSWIgUJVliOjni6LG
"""

# QUESTION 1
import plotly.graph_objects as go
fig= go.Figure()
import seaborn as sns
df=sns.load_dataset('titanic')
fig.add_trace(go.Scatter(x=df['age'],y=df['fare']))
fig.show()

# QUESTION 2
import plotly.express as px
df=px.data.tips()
fig=px.box(df,x='sex',y='total_bill')
fig.show()

# QUESTION 3
import plotly.express as px

df = px.data.tips()
fig = px.histogram(df, x='sex',y="total_bill")
fig.show()

fig=px.histogram(df,x='smoker',pattern_shape='smoker')
fig.show()

fig=px.histogram(df,x='day',color="smoker")
fig.show()

# QUESTION 4
df1=px.data.iris()
fig=px.scatter_matrix(df1,dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],color="species")
fig.show()

# QUESTION 5
'''A Distplot or distribution plot, depicts the variation in the data distribution.'''
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill", y="tip", color="sex", marginal="rug",
                   hover_data=df.columns)
fig.show()